### ISSUE TITLE
oss dispatch错误

### ISSUE THREAD

**Issue by sasachen** [johnlui/AliyunOSS#44]
Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/libs/guzzle/common/Guzzle/Common/AbstractHasDispatcher.php on line 41

 "error_trance": "#0 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/libs/guzzle/common/Guzzle/Common/AbstractHasDispatcher.php(41): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('client.create_r...', Object(Guzzle\\Common\\Event))\n#1 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/libs/guzzle/http/Guzzle/Http/Client.php(450): Guzzle\\Common\\AbstractHasDispatcher->dispatch('client.create_r...', Array)\n#2 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/libs/guzzle/http/Guzzle/Http/Client.php(199): Guzzle\\Http\\Client->prepareRequest(Object(Guzzle\\Http\\Message\\EntityEnclosingRequest), Array)\n#3 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/HttpServiceClient.php(119): Guzzle\\Http\\Client->createRequest('PUT', 'https://os-img-...', Array, Object(Guzzle\\Http\\ReadLimitEntityBody))\n#4 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/HttpServiceClient.php(56): Aliyun\\Common\\Communication\\HttpServiceClient->buildCoreRequest(Object(Aliyun\\Common\\Communication\\HttpRequest))\n#5 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/OpenServiceClient.php(37): Aliyun\\Common\\Communication\\HttpServiceClient->sendRequest(Object(Aliyun\\Common\\Communication\\HttpRequest), Object(Aliyun\\Common\\Communication\\ExecutionContext))\n#6 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/RetryableServiceClient.php(32): Aliyun\\Common\\Communication\\OpenServiceClient->sendRequest(Object(Aliyun\\Common\\Communication\\HttpRequest), Object(Aliyun\\Common\\Communication\\ExecutionContext))\n#7 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/RetryableServiceClient.php(27): Aliyun\\Common\\Communication\\RetryableServiceClient->sendRequestImpl(Object(Aliyun\\Common\\Communication\\HttpRequest), Object(Aliyun\\Common\\Communication\\ExecutionContext), 0)\n#8 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/Common/Communication/Command.php(121): Aliyun\\Common\\Communication\\RetryableServiceClient->sendRequest(Object(Aliyun\\Common\\Communication\\HttpRequest), Object(Aliyun\\Common\\Communication\\ExecutionContext))\n#9 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/OSS/OSSClient.php(429): Aliyun\\Common\\Communication\\Command->execute(Array, Array)\n#10 /data/os/chensha/jpos/vendor/johnlui/aliyun-oss/src/oss/src/Aliyun/OSS/OSSClient.php(153): Aliyun\\OSS\\OSSClient->execute('putObject', Array)\n#11 /data/os/chensha/jpos/library/OSSUpload.php(88): Aliyun\\OSS\\OSSClient->putObject(Array)\n#12 /data/os/chensha/jpos/modules/webapi/site/controllers/SiteController.php(111): app\\library\\OSSUpload->upload()\n#13 [internal function]: app\\modules\\webapi\\site\\controllers\\SiteController->actionUploadImg()\n#14 /data/os/chensha/jpos/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#15 /data/os/chensha/jpos/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)\n#16 /data/os/chensha/jpos/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('upload-img', Array)\n#17 /data/os/chensha/jpos/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('site/site/uploa...', Array)\n#18 /data/os/chensha/jpos/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#19 /data/os/chensha/jpos/web/index-dev.php(12): yii\\base\\Application->run()\n#20 {main}"

**Comment by johnlui** [comment]
laravel 7 以上需要使用 https://github.com/johnlui/AliyunOSS-Laravel7
